name: Auto-Fix Formatting

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix-formatting:
    name: Auto-Fix Code Formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Check and fix formatting
      id: format
      run: |
        # Run pre-commit to fix issues
        pre-commit run --all-files || true

        # Check if there are changes
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes_made=true" >> $GITHUB_OUTPUT
          echo "Formatting fixes applied:"
          git status --porcelain
        else
          echo "changes_made=false" >> $GITHUB_OUTPUT
          echo "✅ No formatting changes needed"
        fi

    - name: Commit and push fixes
      if: steps.format.outputs.changes_made == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add -A
        # Remove [skip ci] to allow CI to run on fixed code
        git commit -m "style: auto-fix formatting violations"
        git push

        echo "✅ Formatting fixes pushed - CI will re-run automatically"

    - name: Success message
      run: |
        if [[ "${{ steps.format.outputs.changes_made }}" == "true" ]]; then
          echo "✅ Formatting violations auto-fixed and pushed"
          echo "CI will now run on the properly formatted code"
        else
          echo "✅ All formatting checks passed"
        fi
