name: Enforce Formatting

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  enforce-formatting:
    name: Enforce Code Formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Use a PAT to allow pushing back to the branch
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Check if formatting is needed
      id: check-formatting
      run: |
        # Run pre-commit and capture exit code
        pre-commit run --all-files || echo "formatting_needed=true" >> $GITHUB_OUTPUT

        # Check if there are any changes after running pre-commit
        if [[ -n $(git status --porcelain) ]]; then
          echo "formatting_needed=true" >> $GITHUB_OUTPUT
          echo "Changes needed:"
          git status --porcelain
        else
          echo "formatting_needed=false" >> $GITHUB_OUTPUT
        fi

    - name: Auto-fix formatting and push back
      if: steps.check-formatting.outputs.formatting_needed == 'true'
      run: |
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Add all changes made by pre-commit
        git add -A

        # Only commit if there are staged changes
        if [[ -n $(git diff --staged --name-only) ]]; then
          git commit -m "style: auto-fix formatting violations [skip ci]"

          # Push the formatting fixes back to the branch
          git push

          # Fail the job to force a re-run with clean code
          echo "❌ Formatting violations were found and auto-fixed."
          echo "The formatting fixes have been pushed to your branch."
          echo "Please pull the latest changes and re-run your workflow."
          exit 1
        fi

    - name: Formatting validation passed
      if: steps.check-formatting.outputs.formatting_needed == 'false'
      run: |
        echo "✅ All formatting checks passed!"
