name: Pre-commit

on:
  push:
    branches: [ main, init ]
  pull_request:
    branches: [ main, init ]

jobs:
  pre-commit:
    name: Pre-commit hooks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run pre-commit hooks
      run: |
        # Install and run pre-commit hooks
        pre-commit install
        pre-commit run --all-files --show-diff-on-failure
      env:
        # Skip tests in pre-commit for speed (covered in main CI)
        SKIP: basic-tests